allowBuilds:
  '@datadog/native-appsec': true
  '@datadog/native-iast-taint-tracking': true
  '@datadog/native-metrics': true
  '@datadog/pprof': true
  '@prisma/client': true
  '@prisma/engines': true
  cpu-features: true
  cypress: true
  dd-trace: true
  esbuild: true
  msw: true
  prisma: true
  protobufjs: true
  sharp: true
  ssh2: true
