name: 🧪 Test
on:
  push:
    branches:
      - master
      - alpha
      - dev
  pull_request: {}

permissions:
  actions: write
  contents: read

jobs:
  #shell:
  #  name: ✓ ShellCheck
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: 🛑 Cancel Previous Runs
  #      uses: styfle/cancel-workflow-action@0.11.0

  #    - name: ⬇️ Checkout repo
  #      uses: actions/checkout@v3

  #    - name: ⎔ Setup ShellCheck
  #      run: sudo apt-get update; sudo apt-get install -y shellcheck

  #    - name: 🔬 Lint
  #      run: |
  #        cd packages
  #        shellcheck  **/*.sh
  #        shellcheck **/atlas-requests
  #        shellcheck **/install
  #        shellcheck **/postinst
  #        shellcheck **/preinst

  lint:
    name: ⬣ Biome
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ⎔ Setup pnpm
        run: corepack enable

      - name: 📥 Download deps
        run: pnpm install

      - name: 🔬 Lint
        run: pnpm run lint

  typecheck:
    name: ʦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ⎔ Setup pnpm
        run: corepack enable

      - name: 📥 Download deps
        run: pnpm install

      - name: 🔎 Type check
        run: pnpm run typecheck --if-present

  vitest:
    name: ⚡ Vitest
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ⎔ Setup pnpm
        run: corepack enable

      - name: 📥 Download deps
        run: pnpm install

      - name: ⚡ Run vitest
        run: pnpm exec vitest --coverage

  cypress:
    name: ⚫️ Cypress
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🏄 Copy test env vars
        run: cp .env.example .env

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: ⎔ Setup pnpm
        run: corepack enable

      - name: 📥 Download deps
        run: pnpm install

      - name: 🐳 Docker compose
        # the sleep is just there to give time for postgres to get started
        run: docker-compose up -d && sleep 3
        env:
          DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/postgres'

      - name: 🛠 Setup Database
        run: pnpm exec prisma migrate reset --force

      - name: ⚙️ Build
        run: pnpm run build

      - name: 🌳 Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: pnpm run start:mocks
          wait-on: 'http://localhost:8811'
        env:
          PORT: '8811'
